version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh 
      - run:
          name: Create Scratch Org
          command: . build/create-scratcg-org.sh  
  deploy-prod:
    docker:
    - iimage: circleci/node:latest
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: . build/install.sh
    -run:
      name: Login to production
      command: . build/setup-prod.sh
    -run:
      name: deploy to production
      command: . build/deploy-prod.sh